management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

resilience4j.retry:
    configs:
      default:
      #2450000000ns -> 10sec
      #2205000000ns -> 9sec
      #1347500000ns -> 5.5sec
      #490000000ns  -> 2sec
      #245000000ns  -> 1sec
      #220500000ns  -> 0.9sec   = 900milli
      #134750000ns  -> 0.55sec  = 550milli
      #49000000ns   -> 0.2sec   = 200milli
      #24500000ns   -> 0.1sec   = 100milli
       waitDuration: 2205000000ns
       enableExponentialBackoff: true
       exponentialBackoffMultiplier: 2
resilience4j.circuitbreaker:
    configs:
      default:
      #2450000000ns -> 10sec
      #2205000000ns -> 9sec
      #1347500000ns -> 5.5sec
      #490000000ns  -> 2sec
      #245000000ns  -> 1sec
      #220500000ns  -> 0.9sec   = 900milli
      #134750000ns  -> 0.55sec  = 550milli
      #49000000ns   -> 0.2sec   = 200milli
      #24500000ns   -> 0.1sec   = 100milli
       waitDurationInOpenState: 2205000000ns
       enableExponentialBackoff: true
       exponentialBackoffMultiplier: 2
       # slowCallDurationThreshold = timelimit
       slowCallDurationThreshold: 9000ms
resilience4j.timelimiter:
    configs:
      default:
      #10000000000(10000ms)  
      #9000000000 (9000ms)   
      #5500000000 (5500ms)   
      #2000000000 (2000ms)   
      #1000000000 (1000ms)   
      #900000000  (900ms)    
      #550000000  (550ms)    
      #200000000  (200ms)    
      #100000000  (100ms)    
      # timeoutDuration = timelimit
        timeoutDuration: 9000000000ns
