management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

resilience4j.retry:
    configs:
      default:
       maxAttempts: 3
resilience4j.circuitbreaker:
    configs:
      default:
        #waitDurationInOpenState: 60000ms
resilience4j.ratelimiter:
    configs:
      default:
        #timeoutDuration: 5s
resilience4j.timelimiter:
    configs:
      default:
        timeOutDuration: 33ms
