management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

resilience4j.retry:
    configs:
      default:
       maxAttempts: 3
resilience4j.circuitbreaker:
    configs:
      default:
        permittedNumberOfCallsInHalfOpenState: 1
        slowCallDurationThreshold: 100ms
resilience4j.ratelimiter:
    configs:
      default:
        limitRefreshPeriod: 500ns
        limitForPeriod: 50
resilience4j.timelimiter:
    configs:
      default:
        timeOutDuration: 100ms
