management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

resilience4j.retry:
    configs:
      default:
      # timeoutduration*12500  = waitDurationInOpenState
      #1250000
      #12500000
      #125000000
       waitDuration: 125000000ns
       enableExponentialBackoff: true
       exponentialBackoffMultiplier: 2
resilience4j.circuitbreaker:
    configs:
      default:
      # timeoutduration*12500  = waitDurationInOpenState
      #1250000
      #12500000
      #125000000
       waitDurationInOpenState: 125000000ns
       enableExponentialBackoff: true
       exponentialBackoffMultiplier: 2
       # slowCallDurationThreshold = timelimit
       slowCallDurationThreshold: 10000ms
resilience4j.timelimiter:
    configs:
      default:
      # timeoutDuration = timelimit/retryMaxAttempts
        timeoutDuration: 3333000000ns
